server:
  port: 8080  # Cổng mà API Gateway sẽ chạy

# Eureka Client configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Địa chỉ Eureka Server
  instance:
    preferIpAddress: true  # Sử dụng địa chỉ IP khi đăng ký service

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway
      - url: /common-service/v3/api-docs
        name: Common Service
  api-docs:
    enabled: true
    path: /v3/api-docs

spring:
  web:
    resources:
      add-mappings: false  # Không thêm mapping của Spring Boot
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5001"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders:
              - X-User-Id
              - X-Username
              - X-Roles
              - Authorization
            allowCredentials: true
            maxAge: 3600
      discovery:
        locator:
          enabled: true  # Cho phép tìm kiếm các service từ Eureka
      # Routes được định nghĩa trong RouteConfig.java
      # Không định nghĩa routes ở đây


# Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    com.duongw.apigatewayservice.filter: DEBUG
    com.duongw.apigatewayservice.client: DEBUG  # Thêm log cho Feign client
    org.springframework.cloud.openfeign: DEBUG # Log chi tiết cho OpenFeign

jwt:
  access: ${JWT_ACCESS_SECRET:HgnVYeMhlFwCuCaTouYDFDVGUpys5Cm1PRgALsOJfxkDpH1ngbxwC02fMT9HZJf19BeP1wuDe4KQoWtbo2QICQ==}