jwt:
  access: ${JWT_ACCESS_SECRET:HgnVYeMhlFwCuCaTouYDFDVGUpys5Cm1PRgALsOJfxkDpH1ngbxwC02fMT9HZJf19BeP1wuDe4KQoWtbo2QICQ==}
  refreshKey: ${JWT_REFRESH_SECRET:NYpuTU1F1j1ziODp9kNfDToZeGPEowi74zfxLKA2l1XtagHNkY9iLOHqeABRQ2kLJ3ae0pv2t8WHWgtx056R5A==}
  resetPassword: ${JWT_RESET_SECRET:hAFks9YZRsf7rVUP1hFuekIwLgkixhZM1yKvovnUlsXgM74GcYNlYFer1MC5BR3uEckBiXOpP0Z1849AdSNYFA===}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:900000} # 15 minutes
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days
  reset-password-expiration: ${JWT_RESET_EXPIRATION:900000} # 15 minutes
  issuer: auth.duongw.com