server:
  port: 8001
#oracle
spring:
  application:
    name: common-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: common
    password: common
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none

#spring docs
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.duongw.commonservice.controller

#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


#minio
minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: job-tracker

logging:
  level:
    org.springframework.web: DEBUG    # Thêm logging để debug
    org.springframework.security: DEBUG

