springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
open:
  api:
    title: Hr database oracle - api service
    server: http://localhost:8000
    description: Server developer 1
    service:
server:
  port: 8000

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: job-tracker
