server:
  port: 8080  # Cổng mà API Gateway sẽ chạy

# Eureka Client configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Địa chỉ Eureka Server
  instance:
    preferIpAddress: true  # Sử dụng địa chỉ IP khi đăng ký service

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway
      - url: /common-service/v3/api-docs
        name: Common Service
  api-docs:
    enabled: true
    path: /v3/api-docs

spring:
  application:
    name: api-gateway-service  # Tên của API Gateway Service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Cho phép tìm kiếm các service từ Eureka
      routes:
      # Các route sẽ được định nghĩa trong RouteConfig.java
      # Các route sẽ được xác định qua Eureka, không cần khai báo trực tiếp tại đây

# Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # Cấu hình mức độ log cho Gateway
    reactor.netty.http.client: DEBUG  # Cấu hình mức độ log cho client HTTP của Reactor

jwt:
  access: ${JWT_ACCESS_SECRET:HgnVYeMhlFwCuCaTouYDFDVGUpys5Cm1PRgALsOJfxkDpH1ngbxwC02fMT9HZJf19BeP1wuDe4KQoWtbo2QICQ==}
